export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_WRONG_CREDENTIALS = 'LOGIN_WRONG_CREDENTIALS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGOUT = 'LOGOUT'

export const CLIENTE_RECUPERAR = 'CLIENTE_RECUPERAR'
export const CLIENTE = 'CLIENTE'
